categories/urls.py
from categories.views import addCategory, categoryListView


from django.urls import path
from . import views
app_name = 'categories'
urlpatterns = [
    path('',views.categoryListView,name ='list'),
    path('add/',views.addCategory, name ='add'),
    path('details/<int:pk>',views.categoryDetailView, name = 'details'),
    path('delete/<int:pk>',views.deleteCategoryView,name ='delete'),
]

config/urls.py
from django.urls.conf import include
from categories.views import categoryListView
from config.settings import MEDIA_ROOT, MEDIA_URL
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('shop.urls'),name ='home'),
    path('list/',include('categories.urls')),
    path('productlist/',include('products.urls')),
    
    
    
] 

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
    path('',views.productListView,name ='productlist'),
    path('addproduct/',views.addProduct, name ='addproduct'),
    path('productdetails/<int:pk>',views.productView, name = 'productdetails'),
    path('deleteproduct/<int:pk>',views.deleteProductView,name ='deleteproduct'),
]

shop/urls.py
from django.urls import path
from django.urls.conf import include
from .views import homePageView, productDetailView
app_name = 'shop'
urlpatterns =[path('',homePageView,name ='home'),
path('<slug:category_slug>/', homePageView, name ='product_by_category'),
path('<slug:category_slug>/<slug:product_slug>/', productDetailView, name ='product_detail'),

]

products/models.py
from django.db import models
from categories.models import Category
from django.urls import reverse

# Create your models here.

# Product Model
class Product(models.Model):
    product_name = models.CharField(max_length= 40, unique= True)
    product_slug = models.SlugField(unique= True)
    product_desc = models.TextField()
    price        = models.DecimalField(max_digits= 7, decimal_places=3)
    product_img  = models.ImageField(upload_to = 'products') 
    category     = models.ForeignKey(Category,on_delete=models.CASCADE) # Deleting a category will automatically delete products of that category

    def __str__(self):
        return self.product_name

    # product url for single product view
    def get_product_url(self):
        return reverse('shop:product_detail',args=[self.category.slug,self.product_slug])
    

products/forms.py
from django.forms import ModelForm
from .models import Product
class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields =('product_name','product_desc','price','category')

products/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Product
from .forms import ProductForm
# Create your views here.
def productListView(request):
    all_products = Product.objects.all()
    context ={'all_products': all_products }
    return render(request, 'productindex.html',context)

def addProduct(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('products:productlist')
    else:
        form = ProductForm()
        
    context_form ={'form':form}
    return render(request,'addproduct.html',context_form)

def productView(request,pk):
    product = get_object_or_404(Product,pk=pk)
    context = {'product':product}
    return render(request,'product.html',context)

def deleteProductView(request,pk):
    product = get_object_or_404(Product,pk=pk)
    product.delete()
    return redirect('products:productlist')

templates/about.html
{% extends 'base.html' %}
{% block content %}
       
     <div class="about-container">
         <h1>WHO WE ARE</h1>
         <hr class = "hr-style">
         Welcome to Buybes, your number one source for all things. Founded in [year] by [founder name], Buybes has come a long way from its beginnings in [starting location]. When [founder name] first started out, [his/her/their] passion for [brand message - e.g. "eco-friendly cleaning products"] drove them to [action: quit day job, do tons of research, etc.] so that Buybes can offer you [competitive differentiator - e.g. "the world's most advanced toothbrush"]. 
         <br> <br> <br> <br> <br>
         <h1>WHAT WE DO</h1>
         <hr class = "hr-style">
         We're dedicated to giving you the very best of products, with a focus on quality, authenticity and experience. We now serve customers all over [place - town, country, the world], and are thrilled that we're able to turn our passion into [my/our] own website.


         <br> <br> <br> <br> <br>
         <h1>OUR MISSION</h1>
         <hr class = "hr-style">

         
         [I/we] hope you enjoy [my/our] products as much as [I/we] enjoy offering them to you. If you have any questions or comments, please don't hesitate to contact [me/us].
         <br>
        
         
     </div>


     
{% endblock content %}

templates/addcategory.html
{% extends 'navbar.html' %}
{% block content %}

<div style="padding : 100px;">
    <h2>Create New Category</h2>
    <hr>
    <br>
    <form method='POST'>{% csrf_token %} 
        <table>
            {{form.as_table}}
    
        </table>
        <br>
        <button type = 'submit'>Save Changes</button>
    </form>
</div>

{% endblock content %}

templates/addproduct.html
{% extends 'navbar.html' %}
{% block content %}

<div style="padding : 100px;">
    <h2>Create New Product</h2>
    <hr>
    <br>
    <form method='POST'>{% csrf_token %} 
        <table>
            {{form.as_table}}
    
        </table>
        <br>
        <button type = 'submit'>Save Changes</button>
    </form>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/homestyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/slidestyle.css' %}">
     
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/0990b594f8.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <!--Navigation Bar -->
    <div class ="topnav ">
      <a class="logo" style="font-size: 1.6rem; font-weight: 600;" >Buy<u>bes</u>.</a>
   
      <a href="#about"><i class ="fas fa-shopping-bag"></i> ORDERS</a>
      <a href="#contact"> <i class="fas fa-shopping-cart"></i> CART</a>
    
      <input type="text" placeholder="Search..">
      <button ><i class = "fa fa-search" aria-hidden="true"></i></button>
      

  </div>
  <!-- Menubar-->
  <div class="menubar">
      <div class="dropdown">
      <button class="dropbtn"> <b>ALL</b> 
            <i class="fa fa-caret-down"></i></button>
            <div class="dropdown-content">
              <a href="#">Link 1</a>
              <a href="#">Link 2</a>
              <a href="#">Link 3</a>
            </div>
      </div>
      <a href="/about.html"><i class="fas fa-home"></i> OUR STORY</a>
      <a href="#"> POPULAR </a>
      <a href="#"><i class = "fa fa-th" aria-hidden="true"></i> ARTICLES </a>
      <div class="dropdown">
          <button class="dropbtn"><b>CUSTOMER SERVICES</b> 
                </button>
                <div class="dropdown-content">
                  <a href="#">Link 1</a>
                  <a href="#">Link 2</a>
                  <a href="#">Link 3</a>
                </div>
          </div>
     
      
          



  </div>
 
   <!-- Slideshow container -->
<div class="slideshow-container">

  <!-- Full-width images with number and caption text -->
  <div class="mySlides fade">
    
    <img src="{% static 'images/clothes.jpeg' %}" style="width:100%">
  </div>

  <div class="mySlides fade">
    <img src="{% static 'images/technology.jpeg' %}" style="width:100%">
  </div>

  <div class="mySlides fade">
    <img src="{% static 'images/covidprotection.jpeg' %}" style="width:100%">
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

{% block content %}
{% endblock %}


    <script src="{% static 'js/script.js' %}" ></script>

    
  </body>
</html>

templates/category_detail.html
{% extends 'navbar.html' %}
{% block content %}
<div style= "padding:100px">
    <h2>CATEGORY : {{category.category_name}}</h2>
    <br>
    <p>{{category.category_desc}}</p>
</div>
{% endblock content %}

templates/contact.html
<h1>
    This is contact page!
</h1>
<p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo necessitatibus inventore sint maiores voluptates vero porro unde deleniti commodi pariatur?
</p>
<p>
    {{ my_text }}
    {{ my_number }}
    
</p>
<ul>
    <li>Item1</li>
    <li>Item2</li>
    <li>Item3</li>
</ul>
<ul>
    {% for each_item in my_list %}
      <li>{{each_item}} </li>
        
    {% endfor %}
</ul>

<ul>
    {% for each_item in my_list %}
    {% if each_item == 122 %}
      <li>{{forloop.counter}}-{{each_item|add:20}}</li>
    {% elif each_item > 122 %}
    <li>{{forloop.counter}}-{{each_item|add:2}}</li>
    {% else %}
    <li>{{forloop.counter}}-{{each_item}}</li>
    {% endif %}
    
        
    {% endfor %}
</ul>

templates/editcategory.html
{% extends 'navbar.html' %}
{% block content %}

<div style="padding : 100px;">
    <h2>Edit Category</h2>
    <hr>
    <br>
    <form method='POST'>{% csrf_token %} 
        <table>
            {{form.as_table}}
    
        </table>
        <br>
        <button type = 'submit'>Save Changes</button>
    </form>
</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}



{% block content %}
<!-- Show category links -->
<h1 class = "heading"> SHOP BY CATEGORY</h1>
      <div style="padding: 70px;">
        <div class="category-row">
<!-- Looping through the context variable to get all the categories-->
          {% for item in categories %}
          <div class="category-column">
            <a href="{{ item.get_absolute_url }}"><img src="{{item.category_img.url}}" alt="{{item.category_name}}" style="height: 120px;width:fit-content" class = "category-image"></a>
            <figcaption class ="category-figcaption">{{item.category_name}}</figcaption>
          </div>
          {% endfor %}

        </div>
      </div>
          
          


    
       <!-- Show product cards -->
<h1 class = "heading"> AVAILABLE NOW </h1>
<div style="padding: 70px;">

    <div class="row">
<!-- Looping through the context variable to get all the products-->
      {% for product in products  %}
      <div class="column">
        <div class="card">
          <a href="{{product.get_product_url}}" target="_blank"><img src="{{product.product_img.url}}" alt="{{product.product_name}}" style ="height :200px; width:fit-content;"></a>
          <h3>{{product.product_name}}</h3>

          <p class="price">${{product.price}}</p>
          <p><button>View Product</button></p>
        </div>
      </div>
      {% endfor %}
        
    </div>
  </div>

  
  
  
              <!-- Pagination -->
        <div class="pagination">
    <!-- Navigate to first and previous pages-->
       {% if products.has_previous %}
         <a href="?page=1">First</a>
      <!--Adjust link to previous page-->
         <a href="?page={{products.previous_page_number}}">&laquo; Previous</a>
       {% endif %}
      <!-- Show current page number--> 
       Page {{products.number}} 

      <!-- Navigate to next pages if any -->
       {% if products.has_next %}
          <a href="?page={{products.next_page_number}}">&raquo; Next</a>
          <a href="?page={{products.p.num_pages}}">Last</a>
       {% endif %}
       <br>
       <br>

     
    
{% endblock %}    
    
        

templates/index.html
{% extends 'navbar.html' %}
{% block content %}
<div style ="padding: 80px">
        <h2>LIST OF CATEGORIES</h2>
        
        <table class="styled-table">
            <thead>
                <tr>
                    <th>NAME OF CATEGORY</th>
                    <th>CHOOSE ACTION</th>
                   
                    
                </tr>
            </thead>
            <tbody>
                {% for item in all_categories %}
                <tr>
                    <td>{{item.category_name}}</td>
                    <td><a href = "{% url 'categories:details' item.id %}"><i class="fas fa-eye "></i></a><a href = "{% url 'categories:delete' item.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a> </td>
                </tr>
                
                {%  endfor %}
                
            </tbody>
        </table>
        <br>
       <i class="fas fa-plus-circle"></i><a href ="{% url 'categories:add' %}"> <u>CREATE A NEW CATEGORY </u></a> 
    </div>
{% endblock content %}

templates/navbar.html
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/homestyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/0990b594f8.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <!--Navigation Bar -->
    <div class ="topnav ">
      <a class="logo" style="font-size: 1.6rem; font-weight: 600;" >Buy<u>bes</u>.</a>
   
      <a href="#about"><i class ="fas fa-shopping-bag"></i> ORDERS</a>
      <a href="#contact"> <i class="fas fa-shopping-cart"></i> CART</a>
    
      <input type="text" placeholder="Search..">
      <button ><i class = "fa fa-search" aria-hidden="true"></i></button>
      

  </div>
  <!-- Menubar-->
  <div class="menubar">
      <div class="dropdown">
      <button class="dropbtn"> <b>ALL</b> 
            <i class="fa fa-caret-down"></i></button>
            <div class="dropdown-content">
              <a href="#">Link 1</a>
              <a href="#">Link 2</a>
              <a href="#">Link 3</a>
            </div>
      </div>
      <a href="/about.html"><i class="fas fa-home"></i> OUR STORY</a>
      <a href="#"> POPULAR </a>
      <a href="#"><i class = "fa fa-th" aria-hidden="true"></i> ARTICLES </a>
      <div class="dropdown">
          <button class="dropbtn"><b>CUSTOMER SERVICES</b> 
                </button>
                <div class="dropdown-content">
                  <a href="#">Link 1</a>
                  <a href="#">Link 2</a>
                  <a href="#">Link 3</a>
                </div>
          </div>
         {% block content %}
         {% endblock content %}
              
          </body>
          </html>

templates/product.html
{% extends 'navbar.html' %}
{% block content %}
<div style= "padding:100px">
    <h2>PRODUCT : {{product.product_name}}</h2>
    <br>
    <p>{{product.product_desc}}</p>
</div>
{% endblock content %}

templates/product_detail.html
{% extends 'navbar.html' %}
{% block content %}

<!-- Single Product Detail -->
<div class ="product-detail" style="margin:70px; border: 1px solid #ddd; ">
    <img src="{{single_product.product_img.url}}" alt="{{single_product.product_name}}" >
    <div style="padding: 90px;">
        <h2>{{single_product.product_name}}</h2>
        <p><b><small>$</small>{{single_product.price}}</b> <br><br>
        <b>Description :</b> <br> {{single_product.product_desc}}</p>
        <br> <br>
        <button style="width:100%">Add to Cart <i class="fas fa-shopping-cart"></i></button>

    </div>
    
       
    </div>
    

{% endblock %}

templates/productindex.html
{% extends 'navbar.html' %}
{% block content %}
<div style ="padding: 80px">
        <h2>LIST OF PRODUCTS</h2>
        
        <table class="styled-table">
            <thead>
                <tr>
                    <th>NAME OF PRODUCT</th>
                    <th>PRICE</th>
                    <th>CATEGORY</th>
                    <th>CHOOSE ACTION</th>
                   
                    
                </tr>
            </thead>
            <tbody>
                {% for item in all_products %}
                <tr>
                    <td>{{item.product_name}}</td>
                    <td>{{item.price}}</td>
                    <td>{{item.category}}</td>
                    <td><a href = "{% url 'products:productdetails' item.id %}"><i class="fas fa-eye "></i></a><a href = "{% url 'products:deleteproduct' item.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a> </td>
                </tr>
                
                {%  endfor %}
                
            </tbody>
        </table>
        <br>
       <i class="fas fa-plus-circle"></i><a href ="{% url 'products:addproduct' %}"> <u>CREATE A NEW PRODUCT </u></a> 
    </div>
{% endblock content %} 